### ISSUE TITLE
crash on selecting game

### ISSUE THREAD

**Issue by MrKev312** [FuryBaguette/AmiiSwap#10]
it crashes when selecting a game in the menu and amiibo's in the emuiibo folder dont show up, i'm on fw version 8.0.1 and kosmos 12.1.2. using version 0.1 of amiiswap does work though

**Comment by JonJaded** [comment]
I don't believe you read the readme properly, The default one included with amiiswap will crash if you don't have the pre-configured amiibos.

**Comment by FuryBaguette** [comment]
^^ That's it.
You should configure the settings.txt, read the readme for a guide.
This will be automated and there will be a setup screen in AmiiSwap next release

**Comment by FuryBaguette** [comment]
It could also be the same problem from #11, check it out.

**Comment by MrKev312** [comment]
it was my settings.txt (btw does it have support for subfolders?)

**Comment by FuryBaguette** [comment]
What do you mean ?

**Comment by MrKev312** [comment]
my amiibo database is organised like /game_name/amiibo_name.bin how would one put that in the settings.txt

**Comment by FuryBaguette** [comment]
If you want to do it like that you can input the amiibo game like this: `game_name/amiibo_name.bin` instead of `amiibo_name.bin` in the settings file, the amiibo name will just not look good in the menu, i'll see what I can do about that to support this folder structure. I would still consider avoiding this if you want to be able to use the next combo with emuiibo.

**Comment by MrKev312** [comment]
does it support spaces in the name and folder?

**Comment by FuryBaguette** [comment]
Yes

**Comment by MrKev312** [comment]
then i'm doing something not correct, this is my settings.txt:
[Super Smash Bros]
01- Super Smash Bros/SSB - 1 Mario

with a whiteline on the end but it causes a crash

**Comment by FuryBaguette** [comment]
It works fine for me, I even tried with your names. When does it crash ?

**Comment by MrKev312** [comment]
when opening the super smash bros folder in amiiswap

**Comment by MrKev312** [comment]
does the amiibo need to be in a folder?

**Comment by FuryBaguette** [comment]
In your case it should be `01- Super Smash Bros/SSB - 1 Mario/amiibo.bin`

**Comment by MrKev312** [comment]
my folder structure is /game/amiibo.bin so shouldn't it be 

> 01- Super Smash Bros/SSB - 1 Mario.bin

**Comment by FuryBaguette** [comment]
No you have to keep the emuiibo setup, so the amiibo should be inside it's own folder with the other data files

**Comment by MrKev312** [comment]
oh ok

**Comment by FuryBaguette** [comment]
Is the issue resolved ?

**Comment by MrKev312** [comment]
yes
