### ISSUE TITLE
[Feature Suggestion] folder as game

### ISSUE THREAD

**Issue by MrKev312** [FuryBaguette/AmiiSwap#12]
It would be nice if you could set a folder as a game:
pros:
easier, clearer and no json needed
cons: 
coding

**Comment by FuryBaguette** [comment]
That's how it worked before but got remove so emuiibo can work properly on it's own. Next release will feature a setup/settings screen to easily create the different games and amiibo lists.

**Comment by MrKev312** [comment]
oh nice, so will this be possible in the next release?

**Comment by FuryBaguette** [comment]
Actually you can set it up like this if you want. But I don't recommend it. Look at this comment: https://github.com/FuryBaguette/AmiiSwap/issues/10#issuecomment-491533747
