### ISSUE TITLE
not every image shows up

### ISSUE THREAD

**Issue by MrKev312** [FuryBaguette/AmiiSwap#13]
not every image for a amiibo will show up, only a few do

**Comment by FuryBaguette** [comment]
Are you sure you have them as amiibo.PNG and not anything else ?

**Comment by MrKev312** [comment]
turns out some were a jpg

**Comment by MrKev312** [comment]
also i made a settings.txt generator for windows: https://github.com/mrbob312/settingstxt_generator/

**Comment by AD2076** [comment]
Nice
