### ISSUE TITLE
when enabled can not back to home

### ISSUE THREAD

**Issue by JustQY** [FuryBaguette/AmiiSwap#15]
i was use odyssey for test,when i enable read amiibo in game,nothing happened,and then i press home button, the console stucked,i must press power button 12 seconds for reboot.
the amiiswap work well,top-right corner show active and file is wedding-mario

**Comment by FuryBaguette** [comment]
Does this behaviour happen inside AmiiSwap or when in your game ? If it's when you're in game then it's most probably a emuiibo problem

**Comment by AD2076** [comment]
wedding-mario and other "special" amiibos can cause issues, can you try another amiibo?

**Comment by JustQY** [comment]
the issue not occur in amiiswap,only console do not have the emuiibo will happen.
i only have 3 amiibos in that game,the others will cause the same issue

**Comment by JustQY** [comment]
i have test what do will occur this.
the console reboot,start odyssey,the enable emuiibo and active one file,back to game,enable read amiibo,nothing happen, press home button (it worked) ,then start another game ,i was zelda,go amiiswap choose file for zelda,enable read amiibo in game,nothing happen too,then press home button,the console will stuck.

no matter what game start first,when second game use amiibo ,the console will occur that issue

**Comment by JustQY** [comment]
my system version is 8.0.1,use ams 0.8.9

**Comment by FuryBaguette** [comment]
Some games like zelda need to have emuiibo emulation turned on before launching the game, you can do that directly inside amiiswap in the emuiibo menu

**Comment by JustQY** [comment]
when i enable emuiibo emulation before launching the game,it not works too,moreover ,this will occur that stuck not launch second game

**Comment by AD2076** [comment]
How do you exit amiiswap before launching the second game?

**Comment by JustQY** [comment]
when first game used amiiswap ,i start another game ,then go amiiswap change file,not disable and reactive the emuiibo,after that ,i press home button directly and back to game for test

**Comment by AD2076** [comment]
Can you try closing amiiswap with +?

**Comment by JustQY** [comment]
when i use + to close amiiswap,the same issue

**Comment by JustQY** [comment]
is it have one method that i can trans my tf-card files to you for test?

**Comment by JustQY** [comment]
[tf-root.zip](https://github.com/FuryBaguette/AmiiSwap/files/3261250/tf-root.zip)
this file is my environment ,amiiswap only

**Comment by FuryBaguette** [comment]
Looks like you didn't follow emuiibo's instructions. You don't create the amiibo folder ect yourself, you just drop them in the emuiibo folder and restart you switch

**Comment by JustQY** [comment]
which step i not  do?

**Comment by JustQY** [comment]
can you share your directory ?thanks a lot

**Comment by FuryBaguette** [comment]
I just told you.
You're missing a bunch of files. So just put all your .bin directly inside emuiibo folder, restart your switch and you'll see that you have more files that what you did and it'll work.

**Comment by JustQY** [comment]
oh yes,it works
thank you,i love you very much

**Comment by FuryBaguette** [comment]
Haha you're welcome, enjoy your amiibos
