### ISSUE TITLE
Amiiswap 1.0 crashes when used with 700+ amiibo bin files....

### ISSUE THREAD

**Issue by Naprosnia** [FuryBaguette/AmiiSwap#18]
The title says it all.

**Comment by AD2076** [comment]
With or without images?

**Comment by Naprosnia** [comment]
With images. All bin files and png images inside their corresponding folders.
Like:
+Mario
+-amiibo.bin
+-amiibo.png
+-amiibo.json
+-mii.dat

**Comment by AD2076** [comment]
amiibo.png shouldn't be there

**Comment by Naprosnia** [comment]
so, where i put image files for each bin file?

**Comment by AD2076** [comment]
https://github.com/FuryBaguette/AmiiSwap/blob/master/README.md

**Comment by Naprosnia** [comment]
i removed all images but it still crashes. Folders now look like:

+sd card root
-+emuiibo
--+2-MP-Peach
----areas
----mii.dat
----amiibo.json
----amiibo.bin
...
--+ (more 732 folders)

On 0.2 version it worked correctly, if i divide 'more or less' 20 amiibos per category on settings files.

I think the problem is when the application tries to read so many amiibos.

**Comment by AD2076** [comment]
It is. Do you really need so many?

**Comment by Naprosnia** [comment]
I do not need them, but since they worked on the previous version, I let them stay.
I select the ones that i need.

**Comment by AD2076** [comment]
1.0 is quite different from 0.2, we are working on this issue. Please use less amiibos or switch back to 0.2 until we release a fix
