### ISSUE TITLE
Crashes Atmosphere when clicking on selected amiibo

### ISSUE THREAD

**Issue by mrdude2478** [FuryBaguette/AmiiSwap#22]
Crashes Atmosphere when clicking on selected Amiibo. 

Atmosphere gives error code 2168-0001 (0x2ae), when you try and select an Amiibo, causes reboot of console.

**Comment by FuryBaguette** [comment]
What is you fw version, which emuiibo version too ?

**Comment by mrdude2478** [comment]
Latest Atomsphere from the downloads section in the releases page on the github. 0.92
Emmubio - latest version from github releases page: 0.3

Ammiswap 1.1 - what's on your github just now :-)

**Comment by FuryBaguette** [comment]
AmiiSwap is not updated for the new emuiibo release. If you still want to use it you'll need to use emuiibo 0.2 or wait for the next update of amiiswap which should come soon.

**Comment by mrdude2478** [comment]
OK, thanks for the reply.
