### ISSUE TITLE
8.1 system + 0.93 atmosphere could not used 

### ISSUE THREAD

**Issue by shallwei** [FuryBaguette/AmiiSwap#23]
Swithch 8.1（no fake system）+ Atomsphere 0.93
Amiiswap 1.0 + Emuiibo 0.23  
In Amiiswap could load the Amiibo.bin and enable Emuiibo(the green lignt up)
In Zelda could not use  and  press the ==> + R-stick no feedback. the home button blue light up mean it could use.
and use the Emuiibo 0.3 could not load the amiibo.bin in Amiiswap.(0.23 could load)

![WechatIMG113](https://user-images.githubusercontent.com/48400414/62875681-05950480-bd56-11e9-93eb-42492a32ed2c.jpeg)

**Comment by jzhjm** [comment]
Emuiibo 0.3 Amiibos go now inside /emuiibo/amiibo/ for a better directory layout.

**Comment by jzhjm** [comment]
> Swithch 8.1（no fake system）+ Atomsphere 0.93
> Amiiswap 1.0 + Emuiibo 0.23
> In Amiiswap could load the Amiibo.bin and enable Emuiibo(the green lignt up)
> In Zelda could not use and press the ==> + R-stick no feedback. the home button blue light up mean it could use.
> and use the Emuiibo 0.3 could not load the amiibo.bin in Amiiswap.(0.23 could load)
> 
> ![WechatIMG113](https://user-images.githubusercontent.com/48400414/62875681-05950480-bd56-11e9-93eb-42492a32ed2c.jpeg)

Amiibos go now inside /emuiibo/amiibo/ for a better directory layout.

**Comment by rgarcia7** [comment]
It seems that new emuiibo 0.3, works different now.
Amiiswap needs to be updated based on this
https://github.com/XorTroll/emuiibo/issues/39
https://github.com/XorTroll/emuiibo/issues/36

**Comment by LyuboA31** [comment]
I have the same issue Amiiswap dosnt work with emuiibo 0.3 no matter where the amibo folders are it needs to be updated 
Btw its not working in atmosphere 0.9.2 too it is working just fine no matter where the amibo folder are with emuiibo 0.21
