### ISSUE TITLE
Unreadable text

### ISSUE THREAD

**Issue by AD2076** [FuryBaguette/AmiiSwap#4]
Text in focused element is unreadable.
I added a simple line of code
`amiiboMenu->SetOnFocusColor({200,200,200,255});`
in MenuLayout function, gonna build and test this evening at home.
Will add a pull request if it works.

**Comment by FuryBaguette** [comment]
> `amiiboMenu->SetOnFocusColor({200,200,200,255});`

You can make a pull request, but please change the color to white

**Comment by AD2076** [comment]
Can't be white, unfocused elements are white :)

**Comment by FuryBaguette** [comment]
Oh yeah got mixed up with text color sorry :/
Well then let's use your color, will see if I'll keep it !
