### ISSUE TITLE
Can not be used on 8.0.1?

### ISSUE THREAD

**Issue by sakatsuku** [FuryBaguette/AmiiSwap#8]
v0.1.3 can be used on 7.0.1, but I update to 8.0.1 today and it doesn't work any more, it not fit for 8.0.1?

**Comment by FuryBaguette** [comment]
AmiiSwap works on any fw, you're probably talking about emuiibo, you have to update it. If I recall correctly you can use the one that comes with [Kosmos](https://github.com/AtlasNX/Kosmos/releases) or look at the emuiibo [gbatemp thread](https://gbatemp.net/threads/emuiibo-mitming-nfp-services-for-amiibo-emulation.536210/)

**Comment by sakatsuku** [comment]
It works on 7.0.1, but after update to 8.0.1, when I open Amiiswap in Homebrew, it shows nothing but only white screen, I use [Atmosphère 0.8.9](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.8.9), so I don't know what happened

**Comment by FuryBaguette** [comment]
It's working perfectly fine for me, are you sure you have created the game folders in the emuiibo folder and that they contain .bin files ?

If that's not the issue I'm not sure what it is, I'll leave the issue open in case it happens to other people, anyways, the new version is more stable and uses a new system for the game folder thing. I'm just waiting for emuiibo to get updated to 0.2 so I can update too.
